### ISSUE TITLE
"The Windows Installer Service could not be accessed."

### ISSUE THREAD

**Issue by DavidBerdik** [DavidXanatos/Sandboxie#1]
It appears that the "Windows Installer Service could not be accessed" error is still present in this release.

![image](https://user-images.githubusercontent.com/7663225/78946109-d921bb80-7a8f-11ea-983d-ab617f594f38.png)

The good news is that now, we can fix it ourselves! That is, we can fix it ourselves if we understand  the code. I've been reading through the code trying to get a sense of how it works, but have admittedly made little to no progress. Do you have any idea how to fix this? Or at least some pointers as to where I should be looking?

Reproducing the issue is very simple: try to run an MSI installer inside a sandbox, and you will get this error.

**Comment by DavidXanatos** [comment]
From 1809 to 1903 MSFT changed something around the "msiServer" service.
On 1809 when trying to install a msi file inside a sandbox, Start.exe starts an sandbox internal instance of that service.
On 1903 it does not even try to start the msiServer.

You can use a tool like TaskExplorer with enabled ETW Monitoring and use the "hold" option (snow flake icon on toolbar) to view all processes running as well as started and terminated.

Anyhow, the fact that Start.exe does not even try to start "C:\Windows\system32\msiexec.exe /V", tells me that most likely a trigger for the service to be started has changed, or is missing entirely, and we need to find an other one.

A good point to start looking is Sandboxie\core\dll\scm.c as it's responsible for services and contains stuff related to MSIServer.

**Comment by DavidXanatos** [comment]
Ok some progress...
It seams in 1809 msiexec.exe calls StartServiceCtrlDispatcher to start the MSIServer service
in 1903 this does not longer happen, so now the question is what starts it and how ini normal operation :/

**Comment by DavidXanatos** [comment]
Fixed on build 5.40.1

**Comment by DavidBerdik** [comment]
Wow! You are amazingly good at this. I am so lost right now reading everything you've done.

If I may ask, where did you find the leaked signing certificate? I am interested in playing with compiling Sandboxie from source and would like to sign it as you have.

**Comment by DavidXanatos** [comment]
I don't think its great if it spreads too much, MSFT may at some point decide to do something against it. But its easy enough to find it was part of a very data leak that was quite prominent in the media.

**Comment by DavidBerdik** [comment]
Yeah, that's fair. I am sure I can find it with a little hunting. I can understand your position.

> But its easy enough to find it was part of a very data leak that was quite prominent in the media.

Unfortunately, this hint encompasses many data leaks. 😂

**Comment by DavidBerdik** [comment]
@DavidXanatos I have found the certificate, and I am trying to use it, but I keep running in to this error. Do you know how I could go about resolving it?

```
Signtool Error: The provided cross certificate would not be present in the certificate chain.
```

**Comment by DavidBerdik** [comment]
I have found the signing certificate, but I am having issues with using it. Would you be willing to share instructions for making use of it?

**Comment by DavidXanatos** [comment]
Try changing the system clock to something 2011

**Comment by DavidBerdik** [comment]
Okay I will. Why is this necessary though? Why can the Sandboxie installer work without without doing this?

**Comment by DavidXanatos** [comment]
No, I meant have the date changed while signing the file and may be drop /t http://timestamp.verisign.com/scripts/timestamp.dll from the command line of the sign tool.

When the file is signed the right way it loads on any windows 10 I tried it on without any issues or additional tricks needed.

**Comment by DavidXanatos** [comment]
And I'm not using pnputil, sandboxie has some own tool to install the driver and in my other projects the driver installation is also "manual" i.e. the tools are creating a service entry pointing to the sys file.

Possibly pnputil has some additional checks which are not present in the windows kernel itself.

**Comment by DavidBerdik** [comment]
I'm not using the timestamp command either. I'm using this.

```
signtool.exe sign /debug /v /a /f "HT Srl.pfx" /p password /n "HT Srl" file.cat
```

**Comment by DavidXanatos** [comment]
don't sign the *.cat file, sign the SbieDrv.sys file directly

**Comment by DavidBerdik** [comment]
Understood. Thank you.

**Comment by ecoeficiente** [comment]
Hi, thanks for the fix. Unfortunately it does not seem to work when the installer tries to launch a second instance of msiec service. 
I have a installer which launches with the fix (did not before) but at the end of the installation the error window gets displayed again.

**Comment by ecoeficiente** [comment]
Well, this problem of launching a second instance of the msiexec service is also present in 1809, so it may be another different issue.

**Comment by deflock** [comment]
@DavidXanatos 
> But its easy enough to find it was part of a very data leak that was quite prominent in the media.
Our asian friends, as always? 😂
Can you write any hash of your cert file? Just to be sure

**Comment by DavidBerdik** [comment]
Here's the MD5 of my pfx `95a91373d774f17f6eedf0850e365c87`.

**Comment by DavidBerdik** [comment]
@deflock Here's the MD5 of my pfx `95a91373d774f17f6eedf0850e365c87`.

**Comment by deflock** [comment]
@DavidBerdik hmm, interesting... Mine starts with `94eabd08...` :)

**Comment by DavidBerdik** [comment]
@deflock Well there are several leaked keys floating around on the internet. So we may all be using different ones, but it should not matter. ☺️

**Comment by DavidXanatos** [comment]
The not starting a second instance issue is indeed a separate problem from it not starting at all, and it seams much more difficult to fix unfortunately.

PS: mine is also the 95a91373d774f17f6eedf0850e365c87 one

**Comment by DavidXanatos** [comment]
Its a pitty that github does not have any sort of private messaging to talk about these things.

**Comment by DavidXanatos** [comment]
@deflock 
is stuf signed with your cert detected by viristotal?

**Comment by DavidXanatos** [comment]
To expand on the second MSI issue a bit:
the second MSI instance is needed for so called "custom actions" that is Code snippets that do something non standard  written by the user.
Like in case of the mumble installer at the very end starting the installed mumble client, for example.

This mechanism uses inter process communication to communicate an that is where it all fails. 
On older version of windows this communication used static names, but microsoft is changing more and more to use dynamic port naming and as far as I understood the issue this mechanism is missing entirely.
So we need to understand it and implement a own copy in the sbie driver.
That is unfortunately its seams quite an advanced task.

**Comment by deflock** [comment]
@DavidXanatos I dont have compile/sign setup yet.
I've got your `SbieDrv.sys` 5.40 from releases and tried to sign it in linux VM.

Not sure I've done it right, but my results:

HT: https://www.virustotal.com/gui/file/34bf4bb484b6df931e498b9efebfe96a6b452ff4651b45b06392bbdbcb44365b/detection

MYCERT: https://www.virustotal.com/gui/file/ebf6a84e6ae597207cac604443fc6f7fd5ee778f4dfa7aadd7b1c9eb928e0d4a/detection

MYCERT + MS cross-certificate file: https://www.virustotal.com/gui/file/027b9f2619f8d58f131eb940944a1508b26c14ab826fcfdd72cc6538c246dba8/detection

**Comment by DavidXanatos** [comment]
your cert seams to work much better substantially less positives.
what is "MS cross-certificate"?

**Comment by deflock** [comment]
`MSCV-XXX.cer` file. Found it in HT archive

**Comment by DavidXanatos** [comment]
ah the one with the md5 starting with ce27078....
hehe.... is did not occurred to me to use this also

so your last test was with the asian + the MS cert form the HT leak?
that seams surprisingly successful.

does the asian has a thumbprint starting with 31e5380e1....
I saw that one on some signed patched drivers but don't have the pfx file

**Comment by deflock** [comment]
> ah the one with the md5 starting with ce27078....

Yes

> does the asian has a thumbprint starting with 31e5380e1....

No, wrote it above already `94eabd08...`

Just google for two words: this repo name and pfx, each in own quotes.
There are a lot of chinese sites, look for keyword: Asia in cert's password 😂
And it's not easy to find valid download link, most of them seem broken.

**Comment by DavidXanatos** [comment]
found it 😁

but when I try to use the MS cert I get "Signtool Error: The provided cross certificate would not be present in the certificate chain."

**Comment by deflock** [comment]
> but when I try to use the MS cert I get "Signtool Error: The provided cross certificate would not be present in the certificate chain."

I've used linux's sign tool. Even more it seems it doesn't require to set date to 2011.

**Comment by DavidXanatos** [comment]
> 
> 
> > but when I try to use the MS cert I get "Signtool Error: The provided cross certificate would not be present in the certificate chain."
> 
> I've used linux's sign tool. Even more it seems it doesn't require to set date to 2011.

HaHa!!!

is there a windows port of it?

**Comment by deflock** [comment]
Not sure it's linux only. Here it is:
https://sourceforge.net/projects/osslsigncode/

**Comment by DavidXanatos** [comment]
> 
> 
> Not sure it's linux only. Here it is: https://sourceforge.net/projects/osslsigncode/

thanks, it says it uses openssl and its opensource so imho with some effort it should compile on windows to...

**Comment by DavidXanatos** [comment]
PS: ah great there is even a guide: https://github.com/mtrojnar/osslsigncode/blob/master/INSTALL.W32.md will try that tomorrow, having to change my clock each time is really annoying....

**Comment by DavidBerdik** [comment]
> ah the one with the md5 starting with ce27078....
> hehe.... is did not occurred to me to use this also

The source from which I got the certificate that I am using has a copy of the ce27078.... certificate with it. I did not think you could sign directly with it though. Is it possible to do so then?

> found it 😁
> 
> but when I try to use the MS cert I get "Signtool Error: The provided cross certificate would not be present in the certificate chain."

What command are you using? I was having this same issue previously. Unfortunately, I do not have any recollection of how I solved it. I will try to go through my browsing history and hard drive to see if I can find how I did it.

> PS: ah great there is even a guide: https://github.com/mtrojnar/osslsigncode/blob/master/INSTALL.W32.md will try that tomorrow, having to change my clock each time is really annoying....

Have you had a chance to try this? I currently do all my signing (not just for Sandboxie), using a dedicated VM. I do not like this "using a sledgehammer to crack a nut" approach. I would really like to use something more lightweight.

**Comment by DavidBerdik** [comment]
@DavidXanatos @deflock 

> ah the one with the md5 starting with ce27078....
> hehe.... is did not occurred to me to use this also

The source from which I got the certificate that I am using has a copy of the ce27078.... certificate with it. I did not think you could sign directly with it though. Is it possible to do so then?

> found it 😁
> 
> but when I try to use the MS cert I get "Signtool Error: The provided cross certificate would not be present in the certificate chain."

What command are you using? I was having this same issue previously. Unfortunately, I do not have any recollection of how I solved it. I will try to go through my browsing history and hard drive to see if I can find how I did it.

> PS: ah great there is even a guide: https://github.com/mtrojnar/osslsigncode/blob/master/INSTALL.W32.md will try that tomorrow, having to change my clock each time is really annoying....

Have you had a chance to try this? I currently do all my signing (not just for Sandboxie), using a dedicated VM. I do not like this "using a sledgehammer to crack a nut" approach. I would really like to use something more lightweight.

**Comment by ecoeficiente** [comment]
> To expand on the second MSI issue a bit:
> the second MSI instance is needed for so called "custom actions" that is Code snippets that do something non standard written by the user.
> Like in case of the mumble installer at the very end starting the installed mumble client, for example.
> 
> This mechanism uses inter process communication to communicate an that is where it all fails.
> On older version of windows this communication used static names, but microsoft is changing more and more to use dynamic port naming and as far as I understood the issue this mechanism is missing entirely.
> So we need to understand it and implement a own copy in the sbie driver.
> That is unfortunately its seams quite an advanced task.

Thanks for the info @DavidXanatos

**Comment by fakuivan** [comment]
![image](https://user-images.githubusercontent.com/15100012/141213061-7bd074da-6017-4515-aaf8-b083ad492191.png)

I'm having this exact problem with Adobe DC.

**Comment by DavidBerdik** [comment]
@fakuivan Are you using an old version of Sandboxie? I haven't had this issue in any releases for well over a year now, and that includes installing Acrobat DC inside Sandboxie.

**Comment by fakuivan** [comment]
@DavidBerdik I'm using Sandboxie Classic v5.53.3 on a Windows Sandbox VM.

**Comment by DavidBerdik** [comment]
> @DavidBerdik I'm using Sandboxie Classic v5.53.3 on a Windows Sandbox VM.

You might want to file a new bug report, then. This one has been marked as resolved for quite a while, so it's unlikely that you will get any attention here.
