### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [DavidXanatos/Sandboxie#4]
I would like to point out that identifiers like “[`_MY_GUISERVER_H`](https://github.com/DavidXanatos/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/core/svc/GuiServer.h#L23 "Update candidate")” and “[`_SBIELOW_J_TABLE`](https://github.com/DavidXanatos/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/core/low/lowdata.h#L38 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by DavidXanatos** [comment]
At some point I guess a refactoring of the code would be in order, but I think that is not one of the things to be done first.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by DavidXanatos** [comment]
Why would you assume its relaying on undefined behavior?
From not adhering to a naming convention to undefined behavior is IMHO quite a long way.

**Comment by elfring** [comment]
Would you like to [delete any underscores in affected identifiers](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for the selection of identifiers in C++")?

**Comment by DavidXanatos** [comment]
mmh... 

When I search for "typedef struct _" in the code I get almost 200 results and there the _ is followed by a Capital latter. 

And this practice to typedef struct _MY_STRUCT {...} MY_STRUCT,*PMY_STRUCT; is extremely popular. 

Apparently the majority of developers agreed to ignore that particular issue.


Look if that would be a few things to change that, I don't care if it makes you happy I would have done it. But its 185 struct definitions, and MSFT's own SDK's and WDK's do the exact same thing. That to me is also a standard violation by the letter, as those are imho not parts of the compiler but external frameworks.
