### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [DavidXanatos/Sandboxie#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CAnimatedBitmap::SetImage](https://github.com/DavidXanatos/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/apps/control/AnimatedBitmap.cpp#L136 "CAnimatedBitmap::SetImage function")
- [CBoxProc](https://github.com/DavidXanatos/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/apps/control/BoxProc.cpp#L61 "Destructor for CBoxProc")
- [CMessageDialog](https://github.com/DavidXanatos/Sandboxie/blob/f22ec96fb1a1fe867bd040ca08b001eb18b864c2/Sandboxie/apps/control/MessageDialog.cpp#L114 "Destructor for CMessageDialog")

**Comment by DavidXanatos** [comment]
meh... you cave a comparison but than you assign a null pointer null again and have a unnecessary call to free. 
if we know that statistically the variables are mostly == 0 than yea that would optimize things, but currently idk. so without the comparison we may end up with waiting more CPU cycles in the end.

Anyhow such minor optimizations are something for much later imho.

**Comment by elfring** [comment]
* Which distribution would you expect (or actually observe) for the passing of null pointers?
* Should pointers for valid objects be usually handled more often?

-----

How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by DavidXanatos** [comment]
I never payed attention to that so idk.
